describe('MyTestSuite', () => {
    it('sign in page', () => {
      cy.visit('https://stgapplicant.vetty.co/login')
      cy.get("#email").type("hitesh95reddy@gmail.com")
      cy.get("#ssn").type("123456")
      cy.get("div.login-button > button").click()
      cy.wait(10000)
      //cy.get("#middleNameCheck").click()
      cy.get("#middlename").clear().type("Kumar")
      cy.get('[placeholder="mm/dd/yyyy"]').clear().type("10171903{enter}")
     
      //cy.get('[placeholder="mm/dd/yyyy"]').click()
      cy.wait(5000)
      cy.get('.modaldobConfirmButton').click()
      cy.get("#ssn").clear().type("012340123")
      //cy.get("#ssn").type("111111111")
      cy.get('[ng-reflect-name=ssn]').clear()
      cy.wait(2500)
      cy.get('[ng-reflect-name=ssn]').type('012')
      cy.wait(2500)
      cy.get('[ng-reflect-name=ssn]').type('34')
      cy.wait(2500)
      cy.get('[ng-reflect-name=ssn]').type('0123')
      cy.wait(2500)

      cy.get('[ng-reflect-name=ssn]').clear()
      cy.wait(2500)
      cy.get('[ng-reflect-name=ssn]').type('012')
      cy.wait(2500)
      cy.get('[ng-reflect-name=ssn]').type('34')
      cy.wait(2500)
      cy.get('[ng-reflect-name=ssn]').type('0123')
      cy.wait(2500)

      cy.get("#street").clear().type("My Address")
      cy.get('#zip').clear().type("12345")
      cy.get("#city").clear().type("ABC")
      cy.get("#phone").clear().type("9999999999")
      cy.get("div.form-box.calforniaWrap > div:nth-child(2) > div:nth-child(2) > div > div").click()
      cy.get(".white-btn").click()
      cy.wait(10000)
      cy.get('[formcontrolname="licenseState"]').select("2: Alaska")
      cy.get('[formcontrolname="licenseNumber"]').clear().type("123456")
      cy.get('[type="file"]').attachFile("images.jpg")
      cy.wait(10000)
      cy.get(".educontinue").click()
      cy.get('.Yes-this-is-correct').click()
      //cy.get(".educontinue").click()
      cy.wait(10000)

      cy.get('[name="institutionName"]').clear().type("ABC")
      cy.get('.degreeDropdown').select("Bachelor")
      cy.get('[name="degreeDescription"]').clear().type("Degree Desc")
      cy.get('[name="major"]').clear().type("Major")
      cy.get('[name="gpa"]').clear().type("9")
      cy.get('[name="nameWhileAttending"]').clear().type("ABC")
      cy.get('[name="middleNameWhileAttending"]').clear().type("MID")
      cy.get('[name="lastNameWhileAttending"]').clear().type("Last")
     
      cy.wait(2500)
      cy.get(':nth-child(1) > app-date > div.ng-untouched > .row > [style="padding-right: 4px;"] > .monthDropdown').select("01")
      cy.wait(2500)
      cy.get(":nth-child(1) > app-date > div.ng-untouched > .row > :nth-child(2) > .dayDropdown").select("2")
      cy.wait(2500)
      cy.get(':nth-child(1) > app-date > div.ng-valid > .row > [style="padding-left: 4px;"] > .yearDropdown').select("2011")
             
      cy.wait(2500)
      cy.get('[style="margin-top:-15px;"] > :nth-child(2) > app-date > div.ng-untouched > .row > [style="padding-right: 4px;"] > .monthDropdown').select("02")
      cy.wait(2500)
      cy.get('[style="margin-top:-15px;"] > :nth-child(2) > app-date > div.ng-untouched > .row > :nth-child(2) > .dayDropdown').select("2")
      cy.wait(2500)
      cy.get('[style="margin-top:-15px;"] > :nth-child(1) > app-date > div.ng-valid > .row > [style="padding-left: 4px;"] > .yearDropdown').select("2011")

      cy.wait(2500)
      cy.get('.inputs > app-date > div.ng-untouched > .row > [style="padding-right: 4px;"] > .monthDropdown').select("03")
      cy.wait(2500)
      cy.get(".inputs > app-date > div.ng-untouched > .row > :nth-child(2) > .dayDropdown").select("2")
      cy.wait(2500)
      cy.get('.inputs > app-date > div.ng-valid > .row > [style="padding-left: 4px;"] > .yearDropdown').select("2011")
     
      cy.get("#street").clear().type("Street")
      cy.get("#city").clear().type("City")
      cy.get("#state").select("AL")
      cy.get("#phone").clear().type("9999999999")
      cy.get("#email").clear().type("email@email.com")
      cy.get(".btnDefault").click()

      cy.wait(10000)

      cy.get('[name="companyname"]').clear().type("ABC")
      cy.get('[name="companytitle"]').clear().type("ABC")
      cy.get("#street").clear().type("ADD")
      cy.get("#zip").clear().type("50005")
      cy.get("#city").clear().type("CITY")
      cy.get("#state").select("AL")
      cy.get("#phone").clear().type("9999999999")
      cy.get("#email").clear().type("hitesh95reddy@gmail.com")
      cy.get("#contactPerson").clear().type("ABC")

      cy.get(":nth-child(1) > .inputs > app-date > div.ng-untouched > .row > .col-md-8 > .monthDropdown").select("01")
      cy.get(":nth-child(1) > .inputs > app-date > div.ng-valid > .row > .col-md-4 > .yearDropdown").select("2012")

      cy.get("div.ng-untouched > .row > .col-md-8 > .monthDropdown").select("02")
      cy.get("div.ng-untouched > .row > .col-md-4 > .yearDropdown").select("2012")
      cy.get(".btnDefault").click()
     
      cy.wait(10000)

      cy.get('[name="certifyingBodyName"]').clear().type("ABC")
      cy.get('[name="licenseType"]').clear().type("TYPE")
      cy.get('[name="licenseType"]').clear().type("1234")
      cy.get(".monthDropdown").select("01")
      cy.get(".yearDropdown").select("2030")
      cy.get(".btnDefault").click()
      cy.wait(10000)


      cy.get('[name="referenceName"]').clear().type("ABC")
      cy.get("#street").clear().type("ADDR")
      cy.get("#zip").clear().type("50005")
      cy.get("#city").clear().type("City")
      cy.get("#state").select("AL")
      cy.get("#phone").clear().type("9999999999")
      cy.get("#email").clear().type("hitesh95reddy@gmail.com")
      cy.get('[value="peer"]').click({force: true})
      cy.get('[value="manager"]').click({force: true})
      cy.get(".btnDefault").click()
      cy.wait(10000)
      cy.get(".btnDefault").click()
      cy.wait(10000)
      cy.get(".btnDefault").click()
      cy.wait(10000)
      cy.get(".btnDefault").click()
      cy.wait(10000)
      cy.get('canvas').click(10,10)
      cy.wait(10000)
    })
  })